src/Entity/HackathonRegistration.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\HackathonRegistrationRepository")
 */
class HackathonRegistration
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $FirstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $LastName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $EmailAddress;

    /**
     * @ORM\Column(type="integer")
     */
    private $PhoneNumber;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Promotion;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NameProject;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $DescribeProject;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreateAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $UpdateAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->FirstName;
    }

    public function setFirstName(string $FirstName): self
    {
        $this->FirstName = $FirstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->LastName;
    }

    public function setLastName(string $LastName): self
    {
        $this->LastName = $LastName;

        return $this;
    }

    public function getEmailAddress(): ?string
    {
        return $this->EmailAddress;
    }

    public function setEmailAddress(string $EmailAddress): self
    {
        $this->EmailAddress = $EmailAddress;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->PhoneNumber;
    }

    public function setPhoneNumber(int $PhoneNumber): self
    {
        $this->PhoneNumber = $PhoneNumber;

        return $this;
    }

    public function getPromotion(): ?string
    {
        return $this->Promotion;
    }

    public function setPromotion(string $Promotion): self
    {
        $this->Promotion = $Promotion;

        return $this;
    }

    public function getNameProject(): ?string
    {
        return $this->NameProject;
    }

    public function setNameProject(string $NameProject): self
    {
        $this->NameProject = $NameProject;

        return $this;
    }

    public function getDescribeProject(): ?string
    {
        return $this->DescribeProject;
    }

    public function setDescribeProject(string $DescribeProject): self
    {
        $this->DescribeProject = $DescribeProject;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->CreateAt;
    }

    public function setCreateAt(\DateTimeInterface $CreateAt): self
    {
        $this->CreateAt = $CreateAt;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->UpdateAt;
    }

    public function setUpdateAt(\DateTimeInterface $UpdateAt): self
    {
        $this->UpdateAt = $UpdateAt;

        return $this;
    }
}

src/Entity/ProjectStudent.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectStudentRepository")
 */
class ProjectStudent
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\HackathonRegistration", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $Author;

    /**
     * @ORM\Column(type="datetime")
     */
    private $CreateAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $UpdateAt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?HackathonRegistration
    {
        return $this->Author;
    }

    public function setAuthor(HackathonRegistration $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->CreateAt;
    }

    public function setCreateAt(\DateTimeInterface $CreateAt): self
    {
        $this->CreateAt = $CreateAt;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->UpdateAt;
    }

    public function setUpdateAt(\DateTimeInterface $UpdateAt): self
    {
        $this->UpdateAt = $UpdateAt;

        return $this;
    }
}

templates/list/list.html.twig
{% extends 'base.html.twig' %}

{% block main %}
        <table class="table text-light">

            <thead>
            <tr>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Email address</th>
                <th scope="col">Phone number</th>
                <th scope="col">Promotion</th>
                <th scope="col">Name project</th>
                <th scope="col">Describe project</th>
                <th scope="col">Inception date</th>
            </tr>
            </thead>
            <tbody>

            {% for project in projects %}
            <tr>
                    <td> {{ project.author.firstName|e }} </td>
                    <td> {{ project.author.LastName|e }}</td>
                    <td> {{ project.author.EmailAddress|e }}</td>
                    <td> {{ project.author.PhoneNumber|e }}</td>
                    <td> {{ project.author.Promotion|e }}</td>
                    <td> {{ project.author.NameProject|e }}</td>
                    <td> {{ project.author.DescribeProject|e }}</td>
                    <td> {{ project.author.CreateAt|date() }}</td>
                <td><button type="button" class="btn btn-warning">Modifier</button></td>
                <td><button type="button" class="btn btn-danger">Supprimer</button></td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endblock %}